export default {
      tabbar_logo: "/assets/images/index/logo.png",
      tabbar_home: "/assets/images/tabbar/index.png",
      tabbar_person: "/assets/images/tabbar/person.png",
      home_logo: "/assets/images/index/home-logo.png",
      home_address: "/assets/images/index/address.png",
      home_certificate: "/assets/images/index/certificate.png",
      home_navLevel: "/assets/images/index/nav-levelExaminate.png",
      home_navTrain: "/assets/images/index/nav-train.png",
      home_navClass: "/assets/images/index/nav-onlineClass.png",
      home_address1: "/assets/images/index/address1.png",
      home_address2: "/assets/images/index/address2.png",
      home_levelBagk: "/assets/images/index/levelBagk.png",
      home_trainBagk: "/assets/images/index/trainBagk.png",
      home_apiClass: "/assets/images/index/class.png",
      home_apiNews: "/assets/images/index/news.png",
      home_eyes: "/assets/images/index/eyes.png",
      home_more: "/assets/images/index/more.png",
      train_coach: "/assets/images/train/coach.png",
      train_coachActive: "/assets/images/train/coach_active.png",
      train_extension: "/assets/images/train/coach.png",
      train_extensionActive: "/assets/images/train/coach_active.png",
      order_bank:"/assets/images/order/bank.png",
      order_weixin:"/assets/images/order/wechart.png",
      order_success:"/assets/images/order/success.png",
      order_right:"/assets/images/order/right.png",
      order_scan:"/assets/images/order/scan_code.png"

}